### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by tahir59** [giantswarm/cert-exporter#91]
hi is there any docker-compose version of it?

**Comment by glitchcrab** [comment]
Hi @tahir59, thanks for your interest in `cert-exporter`! I'm afraid there is no docker-compose manifest as this exporter is intended for use within Kubernetes, but you could create a docker-compose file using the information in this Helm template: https://github.com/giantswarm/cert-exporter/blob/master/helm/cert-exporter/templates/daemonset.yaml

Please do let me know if you have any other questions.
